### ISSUE TITLE
Complete population of gebruiksdoel field

### ISSUE THREAD

**Issue by joostghost** [digitaldutch/BAG_parser#15]
Currently the 'gebruiksdoel' field (purpose of the address) contains just one purpose, for example 'woonfunctie'. But for many addresses there are multiple purposes. For example for zipcode 5109 RK with house number 8, this address has purpose 'Woonfunctie' and 'Industriefunctie'.

See https://bagviewer.kadaster.nl/lvbag/bag-viewer/?searchQuery=5109RK&objectId=0766200000003982&theme=BRT%20Achtergrond&geometry.x=124555.95000000001&geometry.y=407896.92000000004&zoomlevel=15

Another example, zipcode 9145 CG with house number 2 has these purposes: Bijeenkomstfunctie, Gezondheidszorgfunctie, Industriefunctie, Kantoorfunctie, Logiesfunctie, Sportfunctie, Winkelfunctie, Overige gebruiksfunctie.
See https://bagviewer.kadaster.nl/lvbag/bag-viewer/?searchQuery=9145CG&objectId=0058200000245128&theme=BRT%20Achtergrond&geometry.x=193663.91700000002&geometry.y=599703.0519999999&zoomlevel=14.849100227337871

**Comment by digitaldutch** [comment]
Fixed in V63
